version: "3.8"

services:
    php:
        restart: always
        tty: true
        build:
            context: .
            dockerfile: .development/.docker/php/source/Dockerfile
        command: "/docker-entrypoint.sh"
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"
            APP_DOMAIN: ${APP_DOMAIN}
        ports:
            - "${COMPOSE_GATEWAY}:9000:9000"
        volumes:
            - "${COMPOSE_APP_DIR}:${COMPOSE_CONTAINER_DIR}"
            - "${COMPOSE_APP_DIR}/.development/docker/php/php.ini:/usr/local/etc/php/php.ini"
            - "${COMPOSE_APP_DIR}/.development/docker/php/docker-entrypoint.sh:/docker-entrypoint.sh"
        extra_hosts:
            - "host.docker.internal:host-gateway"
